"""
Helper script to easily switch between local and remote database configurations
"""
import os
import shutil
from pathlib import Path

CONFIG_FILE = Path("model/server_info.env")
CONFIG_BACKUP = Path("model/server_info.env.backup")

# Predefined configurations
CONFIGS = {
    "local": {
        "name": "Local PostgreSQL 18",
        "DB_USER": "postgres",
        "DB_PASS": "applyche",
        "DB_HOST": "localhost",
        "DB_PORT": "5434",
        "DB_NAME": "applyche_global"
    },
    "remote": {
        "name": "Remote PostgreSQL Server",
        "DB_USER": "your_username",
        "DB_PASS": "your_password",
        "DB_HOST": "your_server_ip_or_domain",
        "DB_PORT": "5432",
        "DB_NAME": "applyche_global"
    }
}


def backup_config():
    """Create a backup of current configuration"""
    if CONFIG_FILE.exists():
        shutil.copy2(CONFIG_FILE, CONFIG_BACKUP)
        print(f"✓ Backup created: {CONFIG_BACKUP}")


def restore_config():
    """Restore configuration from backup"""
    if CONFIG_BACKUP.exists():
        shutil.copy2(CONFIG_BACKUP, CONFIG_FILE)
        print(f"✓ Configuration restored from backup")
        return True
    else:
        print("✗ No backup found")
        return False


def show_current_config():
    """Display current database configuration"""
    if not CONFIG_FILE.exists():
        print("✗ Configuration file not found!")
        return
    
    print("\n" + "="*60)
    print("Current Database Configuration")
    print("="*60)
    
    with open(CONFIG_FILE, 'r') as f:
        for line in f:
            if line.strip() and not line.startswith('#'):
                key, value = line.strip().split('=', 1)
                # Mask password
                if 'PASS' in key:
                    value = '*' * len(value)
                print(f"  {key}: {value}")
    
    print("="*60 + "\n")


def apply_config(config_type: str):
    """Apply a predefined configuration"""
    if config_type not in CONFIGS:
        print(f"✗ Unknown configuration type: {config_type}")
        print(f"Available types: {', '.join(CONFIGS.keys())}")
        return False
    
    config = CONFIGS[config_type]
    
    # Backup current config
    backup_config()
    
    # Write new configuration
    with open(CONFIG_FILE, 'w') as f:
        f.write(f"# {config['name']} Configuration\n")
        f.write(f"# Generated by switch_db_config.py\n\n")
        for key, value in config.items():
            if key != 'name':
                f.write(f"{key}={value}\n")
    
    print(f"✓ Configuration switched to: {config['name']}")
    print(f"  File: {CONFIG_FILE}")
    
    if config_type == "remote":
        print("\n⚠️  REMEMBER TO UPDATE:")
        print("  - DB_USER: your_username")
        print("  - DB_PASS: your_password")
        print("  - DB_HOST: your_server_ip_or_domain")
        print("  - DB_PORT: your_server_port (usually 5432)")
    
    return True


def interactive_setup():
    """Interactive configuration setup"""
    print("\n" + "="*60)
    print("Database Configuration Setup")
    print("="*60)
    
    print("\nSelect configuration type:")
    print("  1. Local PostgreSQL 18 (localhost:5434)")
    print("  2. Remote PostgreSQL Server")
    print("  3. Custom configuration")
    print("  4. Show current configuration")
    print("  5. Restore from backup")
    print("  0. Exit")
    
    choice = input("\nEnter your choice (0-5): ").strip()
    
    if choice == "1":
        apply_config("local")
    elif choice == "2":
        apply_config("remote")
        print("\n⚠️  Please edit model/server_info.env with your remote server details")
    elif choice == "3":
        custom_setup()
    elif choice == "4":
        show_current_config()
    elif choice == "5":
        restore_config()
    elif choice == "0":
        print("Exiting...")
    else:
        print("✗ Invalid choice")


def custom_setup():
    """Custom configuration setup"""
    print("\n" + "="*60)
    print("Custom Database Configuration")
    print("="*60)
    
    backup_config()
    
    db_user = input("Database User [postgres]: ").strip() or "postgres"
    db_pass = input("Database Password [applyche]: ").strip() or "applyche"
    db_host = input("Database Host [localhost]: ").strip() or "localhost"
    db_port = input("Database Port [5434]: ").strip() or "5434"
    db_name = input("Database Name [applyche_global]: ").strip() or "applyche_global"
    
    with open(CONFIG_FILE, 'w') as f:
        f.write("# Custom Database Configuration\n")
        f.write("# Generated by switch_db_config.py\n\n")
        f.write(f"DB_USER={db_user}\n")
        f.write(f"DB_PASS={db_pass}\n")
        f.write(f"DB_HOST={db_host}\n")
        f.write(f"DB_PORT={db_port}\n")
        f.write(f"DB_NAME={db_name}\n")
    
    print(f"\n✓ Custom configuration saved to {CONFIG_FILE}")


def test_connection():
    """Test database connection"""
    print("\n" + "="*60)
    print("Testing Database Connection")
    print("="*60)
    
    try:
        from api.database import engine
        from sqlalchemy import text
        
        with engine.connect() as conn:
            result = conn.execute(text("SELECT version();"))
            version = result.fetchone()[0]
            print(f"✓ Connection successful!")
            print(f"  PostgreSQL Version: {version}")
            
            # Test database name
            result = conn.execute(text("SELECT current_database();"))
            db_name = result.fetchone()[0]
            print(f"  Connected to database: {db_name}")
            
    except Exception as e:
        print(f"✗ Connection failed: {e}")
        print("\nPlease check:")
        print("  1. PostgreSQL server is running")
        print("  2. Database credentials in model/server_info.env are correct")
        print("  3. Database exists and is accessible")


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) > 1:
        # Command line mode
        command = sys.argv[1].lower()
        
        if command == "local":
            apply_config("local")
        elif command == "remote":
            apply_config("remote")
        elif command == "show":
            show_current_config()
        elif command == "test":
            test_connection()
        elif command == "restore":
            restore_config()
        else:
            print(f"Usage: python switch_db_config.py [local|remote|show|test|restore]")
            print("\nCommands:")
            print("  local    - Switch to local PostgreSQL configuration")
            print("  remote   - Switch to remote PostgreSQL configuration template")
            print("  show     - Show current configuration")
            print("  test     - Test database connection")
            print("  restore  - Restore configuration from backup")
    else:
        # Interactive mode
        interactive_setup()



